language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: C4CrdsnD3/JrLn0BL3k6aDhOKAcYjfVblopUYxP9BPPEOSr3fc+0dE3to8/+G0PdTcJFpDi/us8khz853s2c8n8H4WIKQ8OVL3yhPLo0/E1q2AD2VvWBnhwxvzlXFvypRmOr58v4a6wGbquTVkhLoK3yDAf43lj8AIUTiz6607l9HQhleRRkU38WoeXI1ou6cy0zTqFH57rpvhOpGfncg0Zqk82HIJ3oCJMgdeFlem/ymKaOcUi7sEV0ahs6f7Z8dY3c4d2aXOSR28O0F06ExVQJtkIDFTNjWxKck9uh1tLBA2sPyv8lcM1ubFmZN1mJd2m6Nn2GkVy5rOeHzCdvNpG8t+iezUbFujYyBWzkalDoGHw8Dh9x2DmaoRjfT9y3ya31Zcexf9sO3coFgIQauZgZik4AXvswlfB8dbysHrFv9GfnMutfj3CeIRXD5WXJqua3/BuOfVhKrWM+4YXRvm7iTlfd+nWURAeE5mgesEenF2RzUdYxvmUZgiaafK2uXfyg5bIMa1mfCa5w8B20OfDyow/VQKyLclvWzZinrBcXAEIH73vk7Cjwy2ffxCGphfrU8pvdkcK6WuE31f73sPAgnLz2sCyBQtjqB610S1i7/2XgnhaBcAGyAQ19Qs4/76HuX0ZmLahciuj/122qX8TQd33/EogyNG/kQNZ1UvE=
  app: level-up-games
  on:
    repo: navkelley/levelUp
